export enum Entity {
    NONE = 'model.undefined',
    ACTORS = 'model.entity.actors',
    TRAITS = 'model.entity.traits',
    FLAGS = 'model.entity.flags',
    CHARACTERS = 'model.entity.characters',
    PAPER_DOLL = 'model.entity.paperDoll',
    RELATIONSHIP = 'model.entity.relationship',
    STAFF = 'model.entity.staff',
    AGENCY = 'model.entity.agency',
    COMPANIES = 'model.entity.companies',
    LOCATIONS = 'model.entity.locations',
    CITIES = 'model.entity.cities',
    NATIONS = 'model.entity.nations',
    WORLD_STATE = 'model.entity.world',
}
