export enum EntityType {
    ACTORS = 'model.entity.actors',
    ATTRIBUTES = 'model.entity.attributes',
    EVENTS = 'model.entity.events',
    TRAITS = 'model.entity.traits',
    FLAGS = 'model.entity.flags',
    CHARACTERS = 'model.entity.characters',
    DREAMER = 'model.entity.dreamer',
    PAPER_DOLL = 'model.entity.paperDoll',
    PAPER_PIECE = 'model.entity.paperPiece',
    RELATIONSHIP = 'model.entity.relationship',
    STAFF = 'model.entity.staff',
    AGENCY = 'model.entity.agency',
    COMPANIES = 'model.entity.companies',
    LOCATIONS = 'model.entity.locations',
    CITIES = 'model.entity.cities',
    NATIONS = 'model.entity.nations',
    WORLD_STATE = 'model.entity.world',
}
